client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns = [
    # ex: /webapp/
    path('', views.listUserData, name='listUserData'),

]

myproject/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('webapp/', include('webapp.urls')),
    path('admin/', admin.site.urls),
    path('client/',include('client.urls')),
]

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
    # ex: /webapp/
    path('', views.index, name='index'),
    # ex: /webapp/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /webapp/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /webapp/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('overview/', views.overview, name='overview'),
]

# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
#     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

client/models.py
from django.db import models

# Create your models here.
class SysInfo(models.Model):
    username = models.CharField(max_length=200)
    os = models.CharField(max_length=50)
    compiler = models.CharField(max_length=30)
    cpu_architecture = models.CharField(max_length=20)


    

webapp/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

    def max_vote(self):
        if self.choice_set.all():
            choice = self.choice_set.order_by('votes')[0]
            return choice.choice_text
        else:
            return ''


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

client/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import SysInfo
# Create your views here.


def dispatcher(request):
    #通过request类型修改request.params
    if request.method == 'GET':
        request.params = request.GET
    elif request.method in ['POST','PUT','DELETE']:
        request.params = json.loads(request.body)
    #通过method类型分派给不同的action来实现请求分发
    action = request.params['action']
    if action == 'listUserData':
        return listUserData(request)
    elif action == 'addUserData':
        return addUserData(request)
    elif action == 'deleteUserData':
        return deleteUserData(request)
    elif action == 'modifyUserData':
        return modifyUserData(request)
    else:
        return JsonResponse({'ret':1,'msg':'不支持该类型http请求'})

def listUserData(request):
    #turn query set structured data into json
    qs = SysInfo.objects.values()
    ret_list = list(qs)
    return JsonResponse({'ret':0, 'retlist':ret_list})

def addUserData(request):
    #从request.params获取数据
    info = request.params['data']
    #将转化成python object的data存入数据库
    record =  SysInfo.objects.create(os = info['os'],
                compiler = info['compiler'],
                cpu_architecture = info['cpu_architecture'])
    return JsonResponse({'ret':0,'id':record.id})

def deleteUserData(request):
    user_id = request.params['id']
    try:
        # 根据 id 从数据库中找到相应的记录
        user = SysInfo.objects.get(id=user_id)
    except SysInfo.DoesNotExist:
        return  {
                'ret': 1,
                'msg': f'id 为`{user_id}`的客户不存在'
        }

    # delete 方法就将该记录从数据库中删除了
    SysInfo.delete()
    return JsonResponse({'ret': 0})

def modifyUserData(request):
    user_id = request.params['id']
    new_data = request.params['newdata']
    try:
        user = SysInfo.objects.get(id=user_id)
    except SysInfo.DoesNotExit:
        return{
            'ret':1,
            'msg':f'id为{user_id}的客户不存在'
        }
    if 'os' in new_data:
        SysInfo.os = new_data['os']
    if 'compiler' in new_data:
        SysInfo.compiler = new_data['compiler']
    if 'cpu_architecture' in new_data:
        SysInfo.cpu_architecture = new_data['cpu_architecture']
    SysInfo.save()
    return JsonResponse({'ret':0})

webapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse
from .models import Question, Choice
from django.views import generic
from django.utils import timezone

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)

def detail(request, question_id):
    try:
        prev = 0
        next = 0
        prev_page = True
        next_page = True
        if question_id > 1 and question_id < len(Question.objects.all()):
            prev = question_id-1
            next = question_id+1
        elif question_id > 1 and question_id == len(Question.objects.all()):
            prev = question_id-1
            next_page = False
        else:
            if len(Question.objects.all())==1:
                prev_page = False
                next_page = False
            else:
                next = question_id+1
                prev_page = False
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'webapp/detail.html', {'question': question,
     'prev': prev, 'next': next, 'prev_page': prev_page,
     'next_page': next_page})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if question_id == len(Question.objects.all()):
        pass
    else:
        next = question_id+1
        next_page = True
    return render(request, 'webapp/results.html', {'question': question, 'next': next,
    'next_page': next_page})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'webapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('webapp:results', args=(question.id,)))

def overview(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    questions = Question.objects.all()
    content = {}
    for q in questions:
        content[q] = q.max_vote()
        list(content)
        return render(request, 'webapp/overview.html', {'content':content[q],
        'latest_question_list': latest_question_list})

    
    # return render(request, 'webapp/overview.html', {'content':content,
    # 'latest_question_list': latest_question_list})

webapp/templates/webapp/detail.html
<!-- {{ question }} -->



<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->



<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'webapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

<!-- turn page function -->
{% if prev_page %}
<a href="/webapp/{{prev}}">Prev</a>
{% endif %}
{% if next_page %}
<a href="/webapp/{{next}}">Next</a>
{% endif %}

webapp/templates/webapp/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'webapp/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'webapp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions/choices are available.</p>
{% endif %}

webapp/templates/webapp/overview.html
<h1>Overview</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'webapp:detail' question.id %}">{{ question.question_text }}</a></li>
        <li>{{content}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions/choices are available.</p>
{% endif %}

webapp/templates/webapp/results.html
<!-- <h1>{{ question.question_text }}</h1> -->



<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'webapp:detail' question.id %}">Vote again?</a>
{% if next_page %}
<a href="{% url 'webapp:detail' next %}">Next</a>
{% endif %}